/// Generated by AssetsRefGenerator on 2020/05/24
class Res {
  static const String logo = "assets/img/logo.png";
  static const String perfil1 = "assets/img/perfil1.jpg";
  static const String perfil2 = "assets/img/perfil2.jpg";
  static const String perfil3 = "assets/img/perfil3.jpg";
  static const String perfil4 = "assets/img/perfil4.jpg";
  static const String perfil5 = "assets/img/perfil5.jpg";
  static const String neves = "assets/img/neves.jpg";
  static const String nevesURL = "https://firebasestorage.googleapis.com/v0/b/whatsflutter-330f3.appspot.com/o/perfil%2Fneves.jpg?alt=media&token=981c9555-1096-4265-a218-b91b3b9294a0";
  static const String jesus = "assets/img/jesus.jpg";
  static const String jesusURL = "https://firebasestorage.googleapis.com/v0/b/whatsflutter-330f3.appspot.com/o/perfil%2Fjesus.jpg?alt=media&token=cf5a577d-8925-43fd-aa6d-abecf6490a07";
  static const String marinho = "assets/img/marinho.jpg";
  static const String marinhoURL = "https://firebasestorage.googleapis.com/v0/b/whatsflutter-330f3.appspot.com/o/perfil%2Fmarinho.jpg?alt=media&token=e8589f4d-55cb-41ff-84b3-fdf79d0863c2";
  static const String pombo = "assets/img/pombo.jpg";
  static const String pomboURL = "https://firebasestorage.googleapis.com/v0/b/whatsflutter-330f3.appspot.com/o/perfil%2Fpombo.jpg?alt=media&token=f3e7af69-3be9-465a-9329-09b6ba3696ee";
  static const String fabuloso = "assets/img/fabuloso.jpg";
  static const String fabulosoURL = "https://firebasestorage.googleapis.com/v0/b/whatsflutter-330f3.appspot.com/o/perfil%2Ffabuloso.jpg?alt=media&token=f725077e-f7c9-4079-bb54-cbc711a96fde";
  static const String usuario = "assets/img/usuario.png";
}
