/// Generated by AssetsRefGenerator on 2020/06/03
class Res {
  static const String fabuloso = "assets/img/fabuloso.jpg";
  static const String jesus = "assets/img/jesus.jpg";
  static const String logo = "assets/img/logo.png";
  static const String marinho = "assets/img/marinho.jpg";
  static const String neves = "assets/img/neves.jpg";
  static const String perfil1 = "assets/img/perfil1.jpg";
  static const String perfil2 = "assets/img/perfil2.jpg";
  static const String perfil3 = "assets/img/perfil3.jpg";
  static const String perfil4 = "assets/img/perfil4.jpg";
  static const String perfil5 = "assets/img/perfil5.jpg";
  static const String pombo = "assets/img/pombo.jpg";
  static const String usuario = "assets/img/usuario.png";
}
